Replace `RequestContext` kkwarg `tenant` with `project_id`
cloudbase/coriolis pull request #226
Opened 2022-02-09 13:29 UTC by Dany9966

2022-02-09 13:32 UTC, aznashwan requested changes
Would rather avoid legacy `tenant` attribute altogether.

2022-02-09 14:05 UTC, Dany9966 commented on coriolis/context.py
> +        self.tenant = tenant
Yes, it is accessed in a bunch of places, most commonly by the DB API when getting objects by project_id

2022-02-09 15:10 UTC, aznashwan commented
LGTM. I'd like to run this through proper testing though. (most notably testing minion pools and replica schedules, since they directly depend on the trust setup)

2022-02-10 15:49 UTC, Dany9966 commented
Minion pools and replica schedules have been double-checked.

2022-02-10 15:51 UTC, merged