Batch of unit tests for `ConductorServerEndpoint`
cloudbase/coriolis pull request #256
Opened 2023-04-29 19:10 UTC by smiclea

Based on https://github.com/cloudbase/coriolis/pull/250.
Please merge #250 first.

2023-05-26 16:12 UTC, Dany9966 requested changes
Mostly LGTM

2023-05-27 13:41 UTC, smiclea commented on coriolis/tests/conductor/rpc/data/advance_execution_state.yml
> +      - id: task_1
It's a typo. Should have been a different task id. Fixed now.

2023-05-27 13:47 UTC, smiclea commented on coriolis/tests/conductor/rpc/test_server.py
> +
nice catch!

2023-05-27 13:48 UTC, smiclea commented
@Dany9966  All requested changes have been implemented. Thank you!

2023-08-16 11:23 UTC, merged