Add unit tests for the `events.py` module
cloudbase/coriolis pull request #282
Opened 2023-11-22 12:59 UTC by mihaelabalutoiu

This PR adds unit testing for the `events.py` module.

2023-11-27 11:12 UTC, Dany9966 requested changes

2023-12-06 08:53 UTC, mihaelabalutoiu commented on coriolis/tests/test_events.py
> +    def test_add_percentage_step_negative_total_steps(self, mock_log_warn):
> You got some cases to check, why not try using `ddt`? Should make it easier to test all the cases, in one test method.

Good idea, thank you!

2023-12-06 09:17 UTC, mihaelabalutoiu commented
@Dany9966 I made the changes, please take a look now. Thank you!

2023-12-06 12:14 UTC, Dany9966 requested changes
Mostly LGTM, apart from minor issues

2023-12-06 12:14 UTC, Dany9966 commented on coriolis/tests/test_events.py
> +         'expected_total_steps': 100})
Please add a case where `expected_perc` remains 0, i.e. this `if` is skipped:
https://github.com/cloudbase/coriolis/blob/7b1e26f736b8f6a5f7cfb3cf6cfb4dcc728b2657/coriolis/events.py#L55-L57

2023-12-06 12:14 UTC, Dany9966 commented on coriolis/tests/test_events.py
> +        self.assertLogs(events.LOG, logging.WARN)
Please either remove this `assertLogs`, or fix its usage

2023-12-06 17:31 UTC, merged