Add more unit tests for `coriolis` main modules
cloudbase/coriolis pull request #287
Opened 2024-01-12 13:42 UTC by mihaelabalutoiu

This PR adds more unit testing for the following modules:

* `rpc.py`
* `schemas.py`
* `secrets.py`
* `service.py`
* `utils.py`

2024-01-29 11:46 UTC, Dany9966 requested changes

2024-01-29 11:46 UTC, Dany9966 commented on coriolis/tests/test_wsman.py
> +                         self.conn._conn_timeout)
```suggestion
        self.assertEqual(self.conn._protocol.transport.timeout,
                         self.conn._conn_timeout)
        self.assertEqual(self.conn._protocol.timeout,
                          self.conn._conn_timeout)
```

2024-01-29 11:46 UTC, Dany9966 commented on coriolis/tests/test_wsman.py
> +            shell_id, command_id)
Please also make sure `cleanup_command` and `close_shell` are called.

2024-01-29 11:46 UTC, Dany9966 commented on coriolis/tests/test_wsman.py
> +                          self.conn._exec_command, self.cmd, self.args)
Same as above. Even when exceptions occur, `cleanup_command` and `close_shell` should be called.

2024-01-29 11:46 UTC, Dany9966 commented on coriolis/tests/test_wsman.py
> +            "powershell.exe", ["-EncodedCommand", mock.ANY], timeout=None)
Please add the encoded command string instead of `mock.ANY`

`'dABlAHMAdABfAGMAbQBkAA=='`

2024-01-29 11:46 UTC, Dany9966 commented on coriolis/tests/test_wsman.py
> +            mock.ANY, ignore_stdout=True)
Same as above, add encoded content instead of `mock.ANY`:

`'ZmlsZSBjb250ZW50'`

2024-01-30 16:27 UTC, mihaelabalutoiu reviewed
@Dany9966 I updated the code, take a look now! Thank you!

2024-01-31 12:24 UTC, Dany9966 commented on coriolis/tests/test_rpc.py
> +    @mock.patch('coriolis.rpc.messaging.get_transport')
So it seems like it was indeed necessary. Thanks for pointing it out!

2024-01-31 12:29 UTC, mihaelabalutoiu commented on coriolis/tests/test_rpc.py
> +    @mock.patch('coriolis.rpc.messaging.get_transport')
Indeed, it was necessary for Python version 3.11 :)

2024-01-31 13:26 UTC, merged