Add unit tests for `coriolis/taskflow` modules
cloudbase/coriolis pull request #288
Opened 2024-01-22 10:24 UTC by mihaelabalutoiu

This PR adds unit tests for the following modules:
* `taskflow/runner.py`
* `taskflow/utils.py`
* `taskflow/base.py`

2024-02-20 15:01 UTC, Dany9966 requested changes

2024-02-21 11:33 UTC, mihaelabalutoiu commented on coriolis/tests/taskflow/test_base.py
> +                                                    self.task_failure})
Gotcha! Thank you!

2024-02-21 11:38 UTC, mihaelabalutoiu commented on coriolis/tests/taskflow/test_base.py
> +    def test_set_requires_for_dependencies_with_provides_key(self):
Yes, you are right! Thanks!

2024-02-21 11:41 UTC, mihaelabalutoiu commented on coriolis/tests/taskflow/test_base.py
> +            return_value = ['test']
Good idea!

2024-02-21 11:58 UTC, mihaelabalutoiu commented
Done. I made the changes. Please take a look now, thanks.

2024-02-21 13:19 UTC, Dany9966 approved these changes
LGTM

2024-02-21 13:19 UTC, merged