Add `minion_manager.rpc.client.py/tasks.py` unit tests
cloudbase/coriolis pull request #321
Opened 2024-06-10 12:49 UTC by mihaelabalutoiu

This PR adds test cases for the following module:

- `minion_manager.rpc.tasks.py`
- `minion_manager.rpc.client.py`

2024-07-03 09:06 UTC, Dany9966 requested changes
First review pass done! Please look out for messages (log, event, progress updates, whatever) we do not want to include in tests, and remove all of them please.

2024-08-26 09:01 UTC, mihaelabalutoiu reviewed
I updated the code, please take a look now. Thank you!

2024-08-30 11:55 UTC, Dany9966 requested changes

2024-08-30 11:55 UTC, Dany9966 commented on coriolis/tests/minion_manager/rpc/test_tasks.py
> +            mock.sentinel.action_id, self.allocated_machine_id_mappings)
You don't use `self.allocated_machine_id_mappings` anywhere. You can pass that sentinel directly
```suggestion
        self.task = tasks.ConfirmMinionAllocationForMigrationTask(
            mock.sentinel.action_id,
            mock.sentinel.allocated_machine_id_mappings)
```

2024-08-30 11:55 UTC, Dany9966 commented on coriolis/tests/minion_manager/rpc/test_tasks.py
> +            mock.sentinel.action_id, self.allocated_machine_id_mappings)
Same as above

2024-09-06 12:36 UTC, Dany9966 commented
Mostly lgtm, you only have a little missed case in `HealthcheckMinionMachineTask.execute`. Please handle that too.

2024-09-11 10:08 UTC, Dany9966 requested changes

2024-09-11 10:08 UTC, Dany9966 commented on coriolis/tests/minion_manager/rpc/test_tasks.py
> +        mock_execute.side_effect = CoriolisTestException
I don't get what you're testing here. You mock the tested method, make it raise and then check that the raise has occurred? 
For this case, you need to:
1. set `mock_get_minion_machine.return_value = None`;
2. remove the `mock_execute` entirely;
3. keep `_fail_on_error` on `True`;
4. Check that the call raises `InvalidMinionMachineState`.

2024-09-11 10:58 UTC, Dany9966 commented on coriolis/tests/minion_manager/rpc/test_tasks.py
> +        mock_execute.side_effect = CoriolisTestException
Nevermind this, this case was already covered. This case is also good. Thank you!

2024-09-11 10:59 UTC, Dany9966 approved these changes
LGTM. Thank you!

2024-09-11 10:59 UTC, merged